# Generated by Django 3.1.7 on 2021-06-05 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Defense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=5, verbose_name='Team Name')),
                ('verbose_name', models.CharField(default='', max_length=50, verbose_name='Verbose Name')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=150, null=True)),
                ('admins', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeagueYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2021)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='ffl.league')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('position', models.CharField(default='', max_length=5, verbose_name='Position')),
                ('team', models.CharField(default='', max_length=5, verbose_name='Team')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('week', models.IntegerField(verbose_name='Week')),
                ('points', models.FloatField(default=0.0, verbose_name='Points')),
                ('passing_yds', models.IntegerField(default=0, verbose_name='Passing Yards')),
                ('passing_tds', models.IntegerField(default=0, verbose_name='Passing Touchdowns')),
                ('passing_ints', models.IntegerField(default=0, verbose_name='Passing Interceptions')),
                ('rushing_yds', models.IntegerField(default=0, verbose_name='Rushing Yards')),
                ('rushing_tds', models.IntegerField(default=0, verbose_name='Rushing Touchdowns')),
                ('receiving_yds', models.IntegerField(default=0, verbose_name='Receiving Yards')),
                ('receiving_tds', models.IntegerField(default=0, verbose_name='Receiving Touchdowns')),
                ('kick_ret_tds', models.IntegerField(default=0, verbose_name='Kick Return Touchdowns')),
                ('two_point_conversions', models.IntegerField(default=0, verbose_name='Two Point Conversions')),
                ('fumbles_lost', models.IntegerField(default=0, verbose_name='Fumbles Lost')),
                ('fumbles_rec_tds', models.IntegerField(default=0, verbose_name='Fumble Recovery Touchdowns')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='ffl.player')),
            ],
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(default=1)),
                ('year', models.IntegerField(default=2021)),
                ('qb', models.CharField(max_length=25, verbose_name='Quarterback')),
                ('qb_id', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('qb_points', models.FloatField(default=0.0)),
                ('rb', models.CharField(max_length=25, verbose_name='Running back')),
                ('rb_id', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('rb_points', models.FloatField(default=0.0)),
                ('wr', models.CharField(max_length=25, verbose_name='Wide receiver')),
                ('wr_id', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('wr_points', models.FloatField(default=0.0)),
                ('te', models.CharField(max_length=25, verbose_name='Tight end')),
                ('te_id', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('te_points', models.FloatField(default=0.0)),
                ('defense', models.CharField(max_length=25, verbose_name='Defense')),
                ('defense_id', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('def_points', models.FloatField(default=0.0)),
                ('total_points', models.FloatField(default=0.0)),
                ('pick_time', models.DateTimeField(auto_now_add=True, verbose_name='Date Picked')),
                ('league', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='ffl.leagueyear')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeagueProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(default='', max_length=40, null=True)),
                ('league', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ffl.league')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ffl.league')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitee', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DefenseWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(verbose_name='Week')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('points_allowed', models.IntegerField(verbose_name='Points Allowed')),
                ('sacks', models.IntegerField(verbose_name='Sacks')),
                ('interceptions', models.IntegerField(verbose_name='Interceptions')),
                ('safeties', models.IntegerField(verbose_name='Safeties')),
                ('fumble_recoveries', models.IntegerField(verbose_name='Fumble Recoveries')),
                ('defensive_touchdowns', models.IntegerField(verbose_name='Defensive Touchdowns')),
                ('extra_point_blocks', models.IntegerField(verbose_name='Extra Point Blocks')),
                ('kick_return_touchdowns', models.IntegerField(verbose_name='Kick Return Touchdowns')),
                ('punt_return_touchdowns', models.IntegerField(verbose_name='Punt Return Touchdowns')),
                ('fantasy_points', models.FloatField(default=0.0, verbose_name='Fantasy Points')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week', to='ffl.defense')),
            ],
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(fields=('receiver', 'league'), name='unique_league_invite'),
        ),
    ]
