# Generated by Django 3.1.1 on 2020-09-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='nfl_id',
        ),
        migrations.AddField(
            model_name='player',
            name='id',
            field=models.CharField(default=0, max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerweek',
            name='points',
            field=models.FloatField(default=0.0, verbose_name='Points'),
        ),
    ]
