# Generated by Django 3.1.1 on 2020-09-08 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ffl', '0002_auto_20200901_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerweek',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='ffl.player'),
        ),
    ]
