# Generated by Django 3.1.7 on 2021-06-16 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ffl', '0003_comment_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ffl.thread'),
        ),
        migrations.AlterField(
            model_name='leagueprofile',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ffl.league'),
        ),
        migrations.AlterField(
            model_name='leagueprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='leagueprofile',
            constraint=models.UniqueConstraint(fields=('user', 'league'), name='unique_profile'),
        ),
    ]
