# Generated by Django 3.1.7 on 2021-06-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffl', '0004_auto_20210616_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
