# Generated by Django 3.1.1 on 2020-10-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffl', '0004_pick_defense_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='defense_id',
            field=models.IntegerField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pick',
            name='qb_id',
            field=models.IntegerField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pick',
            name='rb_id',
            field=models.IntegerField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pick',
            name='te_id',
            field=models.IntegerField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pick',
            name='wr_id',
            field=models.IntegerField(blank=True, default=0, max_length=20, null=True),
        ),
    ]
