# Generated by Django 3.1.1 on 2020-10-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffl', '0005_auto_20201029_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='defense_id',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pick',
            name='qb_id',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pick',
            name='rb_id',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pick',
            name='te_id',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pick',
            name='wr_id',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
