# Generated by Django 3.0.2 on 2020-05-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
        ('ffl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='leagues',
            field=models.ManyToManyField(related_name='users', to='ffl.League'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
